name: Sync with upstream

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Save workflow file
        run: |
          mkdir -p .github/workflows_temp
          cp .github/workflows/sync.yml .github/workflows_temp/

      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/ActivityWatch/activitywatch.git
          git fetch upstream master
          git reset --hard upstream/master

      - name: Restore workflow file
        run: |
          mkdir -p .github/workflows
          cp .github/workflows_temp/sync.yml .github/workflows/
          rm -rf .github/workflows_temp

      - name: Commit changes
        run: |
          git add .
          git commit -m "Sync with upstream master" || true

      - name: Push changes
        run: |
          git push -f origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
