name: Sync with upstream

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/ActivityWatch/activitywatch.git
          git fetch upstream

      - name: Sync branches (aggressive approach)
        run: |
          # Сохраняем текущие изменения
          git stash
          
          # Принудительно обновляем до состояния upstream
          git reset --hard upstream/master
          
          # Применяем сохраненные изменения
          git stash pop || true
          
          # Коммитим результат
          git add .
          git commit -m "Sync with upstream/master (aggressive update)" || true

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push -f origin main