name: Sync with upstream

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # Запуск раз в неделю

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Получаем полную историю

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add upstream repository
        run: git remote add upstream https://github.com/ActivityWatch/activitywatch.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: |
          git merge upstream/master --allow-unrelated-histories || {
            echo "Merge conflict occurred. Resolving..."
            git merge --abort
            git reset --hard origin/main
            echo "Please sync manually and resolve conflicts"
            exit 1
          }

      - name: Push changes to origin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main