name: Sync with upstream

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Sync with upstream
        run: |
          # Добавляем и получаем upstream
          git remote add upstream https://github.com/ActivityWatch/activitywatch.git
          git fetch upstream master

          # Сохраняем текущее состояние специфичных файлов если нужно
          # cp your-specific-file.txt /tmp/

          # Сброс к состоянию upstream
          git reset --hard upstream/master

          # Восстанавливаем специфичные файлы если нужно
          # cp /tmp/your-specific-file.txt .

          # Коммитим изменения
          git add .
          git commit -m "Sync with upstream master" || true

      - name: Push changes
        run: |
          git push -f origin main