name: Sync with upstream

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Sync with upstream
        run: |
          # Добавляем upstream
          git remote add upstream https://github.com/ActivityWatch/activitywatch.git
          git fetch upstream

          # Сохраняем текущее состояние
          git checkout -b backup
          
          # Переключаемся на main и синхронизируем с upstream
          git checkout main
          git reset --hard upstream/master
          
          # Применяем специфичные для вашего форка изменения
          git cherry-pick backup || true
          
          # Удаляем временную ветку
          git branch -D backup

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push -f origin main